[phases.setup]
nixPkgs = ['nodejs_20', 'npm-10_x']

[phases.install]
cmds = ['cd dashboard && npm install']

[phases.build]
cmds = ['cd dashboard && npm run build']

[start]
cmd = 'cd dashboard && npm start'
