// Generated types matching the SQL schema

export type Provider = {
  id: string;
  provider_id: string;
  business_name: string;
  slug: string;
  services: string[];
  service_categories: string[];
  specialties: string[];
  service_areas: string[];
  service_postcodes: string[];
  city: string | null;
  state: string | null;
  country: string;
  latitude: number | null;
  longitude: number | null;
  service_radius_km: number;
  emergency_available: boolean;
  response_time: string | null;
  availability_status: 'available' | 'busy' | 'unavailable' | 'on_leave';
  price_tier: 'budget' | 'standard' | 'premium' | 'luxury';
  hourly_rate_min: number | null;
  hourly_rate_max: number | null;
  rating: number | null;
  review_count: number;
  years_experience: number | null;
  licensed: boolean;
  insured: boolean;
  phone: string | null;
  email: string | null;
  website: string | null;
  facebook: string | null;
  instagram: string | null;
  whatsapp: string | null;
  preferred_contact_method: 'phone' | 'email' | 'sms' | 'whatsapp' | 'facebook';
  preferred_lead_types: string[];
  max_leads_per_day: number;
  auto_accept_leads_under: number | null;
  leads_received: number;
  leads_accepted: number;
  leads_converted: number;
  conversion_rate: number;
  avg_response_time_minutes: number | null;
  last_contacted_at: string | null;
  tags: string[];
  notes: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

export type Source = {
  id: string;
  name: string;
  slug: string;
  source_type: 'reddit' | 'facebook_page' | 'forum' | 'directory' | 'classifieds' | 'community_board' | 'website' | 'rss' | 'api';
  base_url: string;
  crawl_config: Record<string, any>;
  status: 'active' | 'paused' | 'error' | 'disabled';
  last_crawled_at: string | null;
  last_error_at: string | null;
  last_error_message: string | null;
  crawl_frequency_minutes: number;
  retry_attempts: number;
  rate_limit_delay_ms: number;
  respect_robots_txt: boolean;
  terms_accepted: boolean;
  terms_accepted_at: string | null;
  compliance_notes: string | null;
  data_retention_days: number;
  posts_crawled: number;
  posts_qualified: number;
  created_at: string;
  updated_at: string;
};

export type RawPost = {
  id: string;
  source_id: string;
  external_id: string | null;
  source_url: string;
  title: string | null;
  content: string;
  content_markdown: string | null;
  raw_html: string | null;
  author_name: string | null;
  author_id: string | null;
  posted_at: string | null;
  scraped_at: string;
  language: string;
  processing_status: 'pending' | 'processing' | 'parsed' | 'failed' | 'spam' | 'duplicate' | 'irrelevant';
  content_hash: string | null;
  duplicate_of: string | null;
  similarity_score: number | null;
  word_count: number | null;
  has_contact_info: boolean;
  created_at: string;
};

export type ParsedIntent = {
  id: string;
  raw_post_id: string;
  service_category: string | null;
  service_confidence: number | null;
  urgency: 'urgent' | 'high' | 'medium' | 'low';
  urgency_score: number;
  budget: 'budget' | 'standard' | 'premium' | 'luxury';
  budget_confidence: number | null;
  locations: string[];
  postcodes: string[];
  detected_city: string | null;
  detected_state: string | null;
  location_confidence: number | null;
  contact_available: boolean;
  preferred_contact_method: string | null;
  phone_numbers: string[];
  emails: string[];
  lead_quality_score: number;
  spam_probability: number;
  is_qualified: boolean;
  signals: Record<string, any>;
  entities: Record<string, any>;
  keywords: string[];
  sentiment: string | null;
  extractor_model: string | null;
  extraction_confidence: number | null;
  created_at: string;
};

export type Lead = {
  id: string;
  lead_number: number;
  raw_post_id: string;
  parsed_intent_id: string;
  title: string | null;
  summary: string | null;
  status: 'new' | 'scored' | 'matched' | 'approved' | 'rejected' | 'contacted' | 'provider_responded' | 'accepted' | 'converted' | 'expired';
  priority_score: number;
  match_count: number;
  top_match_score: number;
  detected_at: string;
  first_matched_at: string | null;
  approved_at: string | null;
  contacted_at: string | null;
  expires_at: string | null;
  assigned_to: string | null;
  notes: string | null;
  tags: string[];
  created_at: string;
  updated_at: string;
};

export type LeadMatch = {
  id: string;
  lead_id: string;
  provider_id: string;
  match_score: number;
  match_reasons: string[];
  service_match_score: number | null;
  location_match_score: number | null;
  urgency_match_score: number | null;
  rating_match_score: number | null;
  price_match_score: number | null;
  availability_match_score: number | null;
  status: 'pending' | 'recommended' | 'approved' | 'rejected' | 'contacted' | 'responded' | 'accepted' | 'declined';
  outreach_sent_at: string | null;
  outreach_method: string | null;
  outreach_template_used: string | null;
  provider_response_at: string | null;
  provider_response: string | null;
  provider_accepted: boolean | null;
  accepted_price: number | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
};

export type OutreachTemplate = {
  id: string;
  name: string;
  template_type: 'sms' | 'email' | 'whatsapp' | 'facebook' | 'dm';
  subject: string | null;
  body: string;
  service_categories: string[];
  urgency_levels: string[];
  price_tiers: string[];
  is_default: boolean;
  usage_count: number;
  created_at: string;
  updated_at: string;
};

export type CrawlJob = {
  id: string;
  source_id: string;
  job_type: 'full' | 'incremental' | 'test';
  status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
  urls_discovered: number;
  urls_crawled: number;
  posts_extracted: number;
  posts_qualified: number;
  errors_count: number;
  started_at: string | null;
  completed_at: string | null;
  duration_seconds: number | null;
  error_message: string | null;
  stack_trace: string | null;
  crawler_version: string | null;
  crawler_node: string | null;
  created_at: string;
};

export type LeadWithRelations = Lead & {
  raw_post: RawPost;
  parsed_intent: ParsedIntent;
  matches?: (LeadMatch & { provider: Provider })[];
};
