/**
 * AI-powered lead analysis generator
 * Uses the provider-agnostic AI service to generate proposals
 */

import { Lead, AIAnalysis } from '@/lib/lead-finder/types';
import { generateText, isAIProposalAvailable, getActiveAIProvider, AI_PROVIDERS } from './ai-service';

/**
 * Generate AI analysis for a lead using the configured AI provider
 */
export async function generateAIAnalysisWithProvider(lead: Lead): Promise<AIAnalysis> {
  // Check if AI is available
  if (!isAIProposalAvailable()) {
    throw new Error('AI proposal generation unavailable — add a free AI provider key in Settings');
  }

  const provider = getActiveAIProvider();
  const providerName = AI_PROVIDERS[provider].name;

  // Build the prompt
  const systemPrompt = `You are an expert sales analyst and copywriter for Demiurge Systems, a digital marketing agency specializing in helping local businesses grow.

Your task is to analyze a business lead and generate a comprehensive sales dossier including:
1. A brief business summary
2. Why this is a good lead
3. Specific problems and opportunities you identified
4. A recommended service package
5. A personalized proposal email
6. A Vapi AI call prompt
7. An opening call script
8. Objection handling responses
9. A follow-up message
10. Internal notes for the sales team
11. Key pain points

Be specific, professional, and persuasive. Use the business details provided to create highly personalized content.`;

  const userPrompt = `Generate a sales analysis for the following business:

Business Name: ${lead.businessName}
Business Type: ${lead.businessType}
Location: ${lead.location}
Address: ${lead.address}
Rating: ${lead.rating || 'N/A'} stars
Review Count: ${lead.reviewCount || 'N/A'}
Website: ${lead.website || 'No website'}
Phone: ${lead.phone || 'N/A'}
Email: ${lead.email || 'N/A'}
Lead Score: ${lead.leadScore}/100

Services: ${lead.services?.join(', ') || 'N/A'}
Opening Hours: ${lead.openingHours ? Object.entries(lead.openingHours).map(([day, hours]) => `${day}: ${hours}`).join(', ') : 'N/A'}

Please provide the analysis in the following JSON format:
{
  "businessSummary": "Brief description of the business",
  "whyGoodLead": "Explanation of why this is a high-value opportunity",
  "problemsOpportunities": ["Array of specific problems and opportunities"],
  "recommendedPackage": "Name and description of recommended service package",
  "personalizedProposal": "Full personalized proposal email text",
  "vapiCallPrompt": "AI prompt for Vapi voice call",
  "openingCallScript": "Sales rep opening call script",
  "objectionHandling": ["Array of objection -> response pairs"],
  "followUpMessage": "Follow-up email/message text",
  "internalNotes": "Internal notes for sales team",
  "painPoints": ["Array of business pain points"]
}`;

  try {
    // Call the AI provider
    const response = await generateText({
      systemPrompt,
      userPrompt,
      temperature: 0.7,
      maxTokens: 3000,
    });

    // Parse the JSON response
    let analysisData: Partial<AIAnalysis>;
    
    try {
      // Try to extract JSON from the response
      const jsonMatch = response.content.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        analysisData = JSON.parse(jsonMatch[0]);
      } else {
        throw new Error('No JSON found in response');
      }
    } catch (parseError) {
      console.error('Failed to parse AI response as JSON:', parseError);
      // Fallback: use the text directly in the proposal field
      analysisData = {
        businessSummary: `${lead.businessName} is a ${lead.businessType} in ${lead.location}.`,
        whyGoodLead: 'This business shows potential for digital marketing services.',
        problemsOpportunities: ['Digital presence optimization needed'],
        recommendedPackage: 'Growth Package',
        personalizedProposal: response.content,
        vapiCallPrompt: `Call ${lead.businessName} about digital marketing services.`,
        openingCallScript: `Hi, this is Demiurge Systems calling about helping ${lead.businessName} grow.`,
        objectionHandling: [],
        followUpMessage: 'Following up on our conversation about digital marketing.',
        internalNotes: `Generated by ${providerName}`,
        painPoints: ['Need more customers'],
      };
    }

    // Build the complete AIAnalysis object
    const analysis: AIAnalysis = {
      generatedAt: new Date().toISOString(),
      businessSummary: analysisData.businessSummary || `${lead.businessName} is a ${lead.businessType} service in ${lead.location}.`,
      whyGoodLead: analysisData.whyGoodLead || `This ${lead.businessType} represents a valuable opportunity in ${lead.location}.`,
      problemsOpportunities: analysisData.problemsOpportunities || [
        !lead.website && 'No professional website - opportunity for web development',
        (lead.rating || 0) < 4.0 && 'Mixed reviews indicate reputation management opportunity',
        'Competitors likely investing in digital marketing',
      ].filter(Boolean) as string[],
      recommendedPackage: analysisData.recommendedPackage || (lead.website 
        ? 'Growth Package: SEO optimization, review management, and social media automation'
        : 'Foundation Package: Professional website, Google Business optimization, and lead capture system'),
      personalizedProposal: analysisData.personalizedProposal || generateFallbackProposal(lead),
      vapiCallPrompt: analysisData.vapiCallPrompt || generateFallbackVapiPrompt(lead),
      openingCallScript: analysisData.openingCallScript || generateFallbackCallScript(lead),
      objectionHandling: analysisData.objectionHandling || [
        'OBJECTION: "We\'re too busy" → RESPONSE: "Our system runs automatically, saving you time."',
        'OBJECTION: "We already have marketing" → RESPONSE: "We enhance what\'s working and fill gaps."',
        'OBJECTION: "How much?" → RESPONSE: "Let\'s discuss your needs on a quick call."',
      ],
      followUpMessage: analysisData.followUpMessage || generateFallbackFollowUp(lead),
      internalNotes: `${analysisData.internalNotes || ''}\n\nProvider: ${providerName}\nGenerated: ${new Date().toISOString()}`,
      painPoints: analysisData.painPoints || [
        'Spending too much time on manual lead follow-up',
        'Missing calls while working on jobs',
        'Competitors showing up higher on Google',
      ],
      // Extended fields
      websiteQualityScore: lead.website ? 70 : 20,
      seoVisibilityEstimate: lead.reviewCount && lead.reviewCount > 50 ? 'medium' : 'low',
      weaknesses: [
        !lead.website && 'No website presence',
        (lead.rating || 0) < 4.0 && 'Below-average rating',
        !lead.email && 'Limited contact options',
      ].filter(Boolean) as string[],
    };

    return analysis;
  } catch (error) {
    console.error('AI generation failed:', error);
    throw new Error(`AI proposal generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

// Fallback template generators
function generateFallbackProposal(lead: Lead): string {
  return `Dear ${lead.businessName} Team,

I've been researching ${lead.businessType} services in ${lead.location} and was impressed by your ${lead.rating ? `${lead.rating}-star reputation` : 'local presence'}.

Demiurge Systems specializes in helping ${lead.businessType}s like yours increase qualified leads by 40-60% through digital marketing automation.

${!lead.website ? 'I noticed you don\'t currently have a website. We can help you establish a professional online presence to capture more leads.' : 'We can enhance your digital presence to attract more customers and outrank competitors.'}

Would you be open to a 15-minute call this week to explore how we can help ${lead.businessName} grow?

Best regards,
Demiurge Systems`;
}

function generateFallbackVapiPrompt(lead: Lead): string {
  return `You are an AI sales assistant calling on behalf of Demiurge Systems for ${lead.businessName}, a ${lead.businessType} in ${lead.location}.

Goal: Book a 15-minute discovery call.

Key points:
- Mention you've researched their ${lead.rating ? 'excellent reviews' : 'local business'}
- You specialize in helping ${lead.businessType}s get more customers
- No obligation, just a quick conversation

Be professional and respectful.`;
}

function generateFallbackCallScript(lead: Lead): string {
  return `"Hi, this is Demiurge Systems. I've been researching ${lead.businessType} services in ${lead.location}, and ${lead.businessName} caught my attention ${lead.rating ? 'with your great reviews' : 'as a local business'}.

We help ${lead.businessType}s get more customers through digital marketing. ${!lead.website ? 'I noticed you don\'t have a website yet' : 'I see some opportunities to improve your online presence'}.

Would you have 15 minutes this week for a quick call?"`;
}

function generateFallbackFollowUp(lead: Lead): string {
  return `Hi ${lead.businessName} team,

Following up on my message about helping ${lead.businessType}s in ${lead.location} grow their customer base.

Quick insights:
• 73% of customers check online reviews before calling
• Businesses with websites get 35% more inquiries
• Automated booking increases appointments significantly

Would love to show you how we can help ${lead.businessName}.

Best regards,
Demiurge Systems`;
}
